# Generated by Django 3.0.11 on 2021-05-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=1000)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
